### PR TITLE
Meet Zynn tests

### PR DESCRIPTION
**Pull request by twiernik**
#549 
Is this quest really a quest? there is no reward, status, progress..

### CODE REVIEW

**Comment by nhnb** [comment]
Most of the Meet* quests are just used for NPC to recognize the player on subsequent interactions.

In this quest file there are some comments which indicates that someone planned to create a proper quest. But that has not happened.

Regarding this test: I am sorry, I don't think, that it adds any value. It basically tests that the NPC engine is able to produce the correct reply to trigger. But that is code that is very well tested anyway.

**Comment by AntumDeluge** [comment]
Should I remove the Meet* quests from #549?

**Comment by nhnb** [comment]
@AntumDeluge Oh, I missed that issue. Yes, please.

**Comment by AntumDeluge** [comment]
Done. Sorry for the confusion @twiernik.

**Pull request closed without merging**
