### PR TITLE
Add Ant Build Options to Create Client Win32 Executable Using Launch4j

### PR DESCRIPTION
**Pull request by AntumDeluge**
<del>This packs the client .jar file into a Win32 executable</del>. It does NOT create any special functionality other than simply allowing Windows users to launch the client from the familiar .exe file type. A compatible Java runtime environment is still necessary for launch. If Java is not found on the system, a dialog is displayed with a link to java.com & notifies the user that Java must be installed.

Changes:
- Adds the [Launch4j](http://launch4j.sourceforge.net/) <del>& [Jsign](https://ebourg.github.io/jsign/)</del> libraries/utilities for creating <del>& signing</del> Win32 executable from Java .jar files.
- Separates ***dist_client_binary*** target into ***dist_client_binary*** & ***stage_dist_client***.
- Adds the following new ant build targets:
  - <del>***launch4j***: Pack client .jar into Win32 executable</del>
  - ***launch4j***: Create Win32 executable that calls client .jar
  - <del>***signexe***: Sign Win32 executable using JSign</del>
  - ***stage_dist_client_exe:*** Calls *stage_dist_client* & copies Win32 executable to stage dir
  - ***dist_client_exe***: Create distributable .zip package with Win32 executable

**Edit:** .jar is now called from Win32 executable instead of being packed into it.

### CODE REVIEW

**Comment by nhnb** [comment]
If I understand the website correctly, launch4j supports both wrapping and calling. I think we should use calling stendhal-starter.jar instead of wrapping it. So we can just include the .exe file in the normal download.

The launch4j libraries should go into buildtools instead of lib.

Is signing required for a .exe file? Our code signing certificate expired.

**Comment by AntumDeluge** [comment]
Signing is only suggested for wrapping, I believe, to avoid issues with anti-virus software according to the warning message. So, I will change it to use wrapping instead & we shouldn't need the *signexe* target.

And, as I said before, this is just a suggestion & really doesn't add anything to the user experience except for give Windows users a familiar .exe executable & a popup message if Java is not installed correctly.

**Comment by AntumDeluge** [comment]
Okay, I moved Luanch4j into *buildtools* directory. And I changed the build to make the Win32 executable call the .jar instead of pack it. I also removed the Jsign utility & the *signexe* build targets as they are not necessary without packing.

I will also modify the build so that it creates a single distribution .zip instead of creating a separate one for the .exe.

**Comment by AntumDeluge** [comment]
So, currently this won't work on Linux systems because native binaries are required for the ***windres*** & ***ld*** commands. Which are available from ***Launch4j***. I'm just wondering if there is a better cross-platform way to implement this.

**Comment by nhnb** [comment]
I pushed a simplified version of this PR because it turned out, that launch4j is not actually compiling source code into a .exe file. Instead it links pre-compiled and attaches the configuration as embedded text resource. 

Therefore it does not make much difference, whether we generate the stendhal-starter.exe based on pre-compiled launch4j-code during build or just include a pre-compiled stendhal-starter.exe.

I am not really happy with include pre-compiled code, but building mingw static libraries as part of our build is way out of scope for Stendhal

**Pull request closed without merging**
