### PR TITLE
fix Hackim Easso trapping players forever

### PR DESCRIPTION
**Pull request by ToBeFree**
...by moving the last/first node one field down.

### CODE REVIEW

**Comment by ToBeFree** [comment]
This is about issue #61

**Comment by ToBeFree** [comment]
what is this codecov thing talking about? I changed one number

**Comment by AntumDeluge** [comment]
Ya. Seems like a lot of output for such a simple commit. :smile:

**Comment by AntumDeluge** [comment]
There is another solution I believe. Entities can be set to reverse their path when they collide with a player. I had to do this with an NPC whose path is along a narrow stretch. Look at [FlowerGirlNPC](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/maps/nalwor/flowershop/FlowerGrowerNPC.java#L79) code & [CollisionAction](https://github.com/arianne/stendhal/blob/master/src/games/stendhal/server/entity/CollisionAction.java). I believe that STOP is the default action.

And, even though changing the NPCs path in this case is not a big deal at all, I would prefer a solution that doesn't do this if possible.

**Comment by ToBeFree** [comment]
I should setup a development environment instead of blindly commiting. 😳

**Comment by AntumDeluge** [comment]
Merged as commit 0501454.
Thank you @ToBeFree.

**Pull request closed without merging**
