### PR TITLE
Buttons on intro page made semitransparent

### PR DESCRIPTION
**Pull request by hajdam**
Modified rendering of game start window and buttons to be semitransparent.

If agreed, I would also would like to maybe add some animations / rework it further as well as credits, login window / server profiles...

### CODE REVIEW

**Comment by nhnb** [comment]
image

I guess, those buttons are not supposed to look like this. I am on Ubuntu 22.04 with OpenJDK Runtime Environment 1.8.0_382-8u382-ga-1~22.04.1-b05

**Comment by hajdam** [comment]
Well, primary modification was to scale image directly without creating new image every time which was slow on my system...
It actually looks same on my system, but because I was testing it with stone background instead of wood, I kept transparency a bit too high (127)...
2023-09-03-002638_640x480_scrot
Other option would be to go with non-opaque buttons which would be same regardless of client style option:
2023-09-03-003451_640x480_scrot

**Comment by kiheru** [comment]
I have no idea if we actually want this, but commenting on the implementation:
Making the buttons semitransparent is easier by calling setOpaque(false) to all of them, and then override paintChildren() of the container to draw the the subcomponents with the desired alpha.

**Comment by AntumDeluge** [comment]
I'm actually not fond of the semi-transparent buttons.

**Comment by hajdam** [comment]
Well, let's scrap this then. I assumed semi-transparent button would be acceptable, because newer Stendhal JS/Android client has semi-transparent stripe too.

Question remains, what other modifications I could make would be acceptable:
- Center start window on screen
- Add background music same as in JS/Android client
- Make credits window scrollable
- Modify login/server profiles to be more similar to JS/Android client
- Add some small animation

Or whether priority is on gameplay content and I should not be distracting with minor GUI changes.

**Comment by AntumDeluge** [comment]
> ...what other modifications I could make would be acceptable:
>
> * Center start window on screen
> * Add background music same as in JS/Android client
> * Make credits window scrollable
> * Modify login/server profiles to be more similar to JS/Android client
> * Add some small animation


* Center start window on screen

    Currently it uses the window position stored after login. Some players might still prefer that. But if it a configuration option that can be enabled/disabled it should be fine.

* Make credits window scrollable

    Not sure about this one. Currently it is an animated window that scrolls through credits automatically (is it not working for some people?).

* Modify login/server profiles to be more similar to JS/Android client

    Are you talking about the character select screen?

    image

The rest seem fine to me.

**Comment by hajdam** [comment]
>     * Center start window on screen
>       Currently it uses the window position stored after login. Some players might still prefer that. But if it a configuration option that can be enabled/disabled it should be fine.

This is how stendhal starts on my screen with my resolution. Main window is fine and I use it maximized.

screenshot
 
>     * Make credits window scrollable
>       Not sure about this one. Currently it is an animated window that scrolls through credits automatically (is it not working for some people?).

I mean, it's ok if you are fine with that.. I doubt many people red it as it runs for 5 minutes and it scrolls somewhat slow...
 
>     * Modify login/server profiles to be more similar to JS/Android client
>       Are you talking about the character select screen?

No, I'm talking about login/server profiles as open in screenshot above in contrast to login flow in JS/Android here:

Screenshot_20231031-122715

Which leads to login page: https://stendhalgame.org/account/login.html

I believe simple login to main server in Java client as default workflow would be more appealing. There could be button to add alternative server, but I believe 99% of users would have no reason to use it...

> **EDIT:** Also, in regards to semi-transparent buttons, if it could be enabled/disabled as a configuration option, I would be okay with it.

That would seem like useless option, lets just keep it opaque. But semi-transparency could be maybe utilized in main window somewhere, or at least I think it was mentioned in some issues somewhere.

**Comment by AntumDeluge** [comment]
> This is how stendhal starts on my screen with my resolution. Main window is fine and I use it maximized.
> 
> screenshot

Okay, I see what you mean. It would make sense for the startup screen to be centered when client starts maximized.

> No, I'm talking about login/server profiles as open in screenshot above in contrast to login flow in JS/Android here:
> 
> Screenshot_20231031-122715
> 
> I believe simple login to main server in Java client as default workflow would be more appealing. There could be button to add alternative server, but I believe 99% of users would have no reason to use it...

Sorry, I'm not fully understanding. The main server is the default in the Java client & can be changed simply by editing the server name field.

That build of the Android client in your screenshot is a debug build. That is why it gives you the option to select main or testing. Release builds default to main server on stendhalgame.org, but it can be customized in settings.

**Comment by hajdam** [comment]
> Sorry, I'm not fully understanding. The main server is the default in the Java client & can be changed simply by editing the server name field.

It was just that a typical player won't be changing server/port fields, so I was considering slightly different approach with server profiles and player profiles.

Anyway, closing this.

**Pull request closed without merging**
